### ISSUE TITLE
`minifiedUrl` in `uploadSourceMap` is incorrectly handling URI strings

### ISSUE THREAD

**Issue by clindsey** [bakunyo/bugsnag-sourcemap-webpack-plugin#2]
The call to `path.join` uses a URI as the first argument, which causes issues in the output string.

https://github.com/bakunyo/bugsnag-sourcemap-webpack-plugin/blob/master/src/BugsnagSourceMapPlugin.js#L55

If `this.publicPath` is `http://some.url/path/` and `sourceFile` is `bundle.js`, the value of `minifiedUrl` will be `http:/some.url/path.bundle.js`.  Notice how it's missing the 2nd `/` after `http:`.

**Comment by bakunyo** [comment]
@clindsey Thanks for your comment.
I want to define `publicPath` is both available `http://some.url/path` and `http://some.url/path/` .
So I will use [url-join](https://github.com/jfromaniello/url-join) after merge your PR.
